name: ML Pipeline Execution
on: [push, workflow_dispatch]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install jupyter nbconvert

    - name: Run Data Preprocessing
      run: |
        jupyter nbconvert --execute --to notebook --inplace Preprocesamiento.ipynb

    - name: Run Model Training
      run: |
        jupyter nbconvert --execute --to notebook --inplace Entrenamiento.ipynb

    - name: Run Visualization
      run: |
        jupyter nbconvert --execute --to notebook --inplace Visualizacion.ipynb

    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: pipeline-results
        path: |
          mejor_modelo.keras
          grafica_mejor_modelo.png
          mlruns/
        retention-days: 1
